In [2]:
import requests
! wget https://huggingface.co/datasets/DarwinAnim8or/the-verdict/resolve/main/the-verdict.txt

--2025-03-11 22:53:51--  https://huggingface.co/datasets/DarwinAnim8or/the-verdict/resolve/main/the-verdict.txt
Resolving huggingface.co (huggingface.co)... 54.192.171.40, 54.192.171.56, 54.192.171.53, ...
Connecting to huggingface.co (huggingface.co)|54.192.171.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20643 (20K) [text/plain]
Saving to: ‘the-verdict.txt’

the-verdict.txt     100%[===================>]  20.16K  --.-KB/s    in 0s      

2025-03-11 22:53:51 (74.8 MB/s) - ‘the-verdict.txt’ saved [20643/20643]



In [3]:
with open("the-verdict.txt", "r") as f:
    text = f.read()
    


In [5]:
import re
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)

In [8]:
result = [item for item in result if item.strip()]


In [12]:
vocab = {}
for i, char in enumerate(set(result)):
    vocab.update({i: char})

In [14]:
vocab

{0: 'fact',
 1: 'wincing',
 2: 'ah',
 3: 'genius',
 4: 'bronzes',
 5: 'earth',
 6: 'won',
 7: 'made',
 8: 'boudoir',
 9: 'each',
 10: 'modest',
 11: 'manage',
 12: 'jealousy',
 13: 'fewer',
 14: 'stocked',
 15: 'cigar',
 16: 'put',
 17: 'grayish',
 18: 'twenty',
 19: 'weeks',
 20: 'distinguished',
 21: 'showed',
 22: 'enlightenment',
 23: 'swelling',
 24: 'their',
 25: 'something',
 26: 'than',
 27: 'bath-rooms',
 28: 'forgive',
 29: 'merely',
 30: 'are',
 31: 'circus-clown',
 32: 'business',
 33: 'three',
 34: 'immediately',
 35: 'found',
 36: 'answered',
 37: 'open',
 38: 'exasperated',
 39: 'managed',
 40: 'dining-room',
 41: 'life',
 42: 'beaming',
 43: 'breaking',
 44: 'whole',
 45: 'had',
 46: 'mediocrity',
 47: 'fragments',
 48: 'Grindle',
 49: 'villa',
 50: 'upon',
 51: 'Professional',
 52: 'Usually',
 53: 'hanging',
 54: 'll',
 55: 'arm',
 56: 'laid',
 57: 'them',
 58: 'preliminary',
 59: 'brought',
 60: 'line',
 61: 'left',
 62: 'Rome',
 63: 'come',
 64: 'understand',
 65: 'w

In [15]:

class Tokenizer:
    def __init__(self, vocab):
        self.vocab = vocab
        self.reverse_vocab = {v: k for k, v in vocab.items()}
        
    def encode(self, text):
        result = [self.reverse_vocab[char] for char in text.split()]
        return result
    
    def decode(self, text):
        result = [self.vocab[char] for char in text]
        return result

tokenizer = Tokenizer(vocab)
            
    

In [17]:
input_ids = tokenizer.encode("this is me")

In [18]:
tokenizer.decode(input_ids)

['this', 'is', 'me']

# Implementing gpt-2 tokenizer: byte pair tokenization


In [21]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")

In [31]:
tokenizer.encode("Goldy")

[13306, 88]

In [33]:
tokenizer.decode([13306])

'Gold'

In [34]:
tokenizer.n_vocab

50257

In [53]:
# create embedding
from torch import nn
import torch as th
embedding = nn.Embedding(50257, 30)
embedding

Embedding(50257, 30)

In [50]:
text = "hello world I am david"
input_ids = tokenizer.encode(text)
input_ids

[31373, 995, 314, 716, 21970]

In [57]:
input_ids.append(50257)

In [58]:
embedding(th.tensor(input_ids))

IndexError: index out of range in self

In [59]:
input_ids.pop()


50257

In [64]:
embedding(th.tensor(input_ids))

tensor([[-0.0259, -0.5521, -0.5025, -0.3852, -1.4487,  1.4313,  0.2164,  2.5713,
         -2.0453, -2.7857,  0.3548,  0.3638,  0.7200,  0.0764,  0.5517, -1.1394,
          1.0832,  0.4797,  0.8990,  0.6999,  0.4831,  0.9679,  0.3531,  1.1215,
         -1.8228, -0.7453, -1.4307,  0.2551,  0.9244, -0.8466],
        [-1.1311, -0.6478,  0.2392, -1.4520, -0.9225,  0.2910,  0.2690,  0.6221,
          0.1687, -0.1037,  0.9916, -0.8624, -0.3141,  0.4049, -2.1015, -0.5437,
         -0.5810, -1.0365,  1.5048, -0.2985, -0.2319, -1.8894, -0.4477, -0.7516,
         -0.2900, -0.5333, -1.0394,  0.9508,  0.4055,  0.6297],
        [-0.8966, -1.0196,  1.9796, -0.2025, -0.9479, -0.3666, -0.6847, -0.6036,
          0.2575,  0.9518, -0.5309,  0.0287,  0.0978, -0.5788,  0.7436,  0.5281,
          0.3474, -0.9728, -0.3496, -0.9444, -0.3704,  0.5735,  0.5776, -1.0375,
          0.7985, -0.7299,  0.2381,  0.3774, -1.9297, -1.9548],
        [-1.6444,  0.3790, -1.5907, -1.7007, -0.1432,  0.4124,  1.0695, -0.1098

In [65]:
embedding.weight

Parameter containing:
tensor([[ 2.4606,  0.6403,  1.4206,  ...,  1.8374,  0.6385, -0.8951],
        [-1.6925, -0.2427, -0.5589,  ..., -0.5965,  0.5449,  2.3124],
        [-1.4291,  1.3848, -0.1998,  ..., -0.8891,  0.6038, -0.6890],
        ...,
        [ 0.1949, -0.5486,  1.8007,  ..., -1.2415, -1.2682, -0.0598],
        [ 1.6684,  1.0297, -1.8269,  ...,  0.3577,  0.2386,  1.1856],
        [ 1.9408,  0.7011, -1.3596,  ..., -1.1146, -0.2969,  1.8117]],
       requires_grad=True)

In [66]:
sentence = "The cat sat on the mat and jumped over the moon"
input_ids = tokenizer.encode(sentence)
input_embedding = embedding(th.tensor(input_ids))

In [68]:
input_embedding.shape

torch.Size([11, 30])

In [71]:
attention_weight = input_embedding @ input_embedding.T
attention_weight.shape, attention_weight

(torch.Size([11, 11]),
 tensor([[ 27.0889,  -0.7738,  -2.1060,  -1.0440,  -4.9437,   1.7081,  -9.0385,
           -8.6069,   2.0684,  -4.9437,   1.1981],
         [ -0.7738,  23.0050,  -0.4378,   6.3445,  -4.0576,   1.0195,   0.6002,
            3.7368,   8.4872,  -4.0576,  -6.4198],
         [ -2.1060,  -0.4378,  29.5684,   4.5297,  -0.4493,   5.0289, -12.9330,
            5.0130,   2.0453,  -0.4493,   0.0544],
         [ -1.0440,   6.3445,   4.5297,  35.4474,   0.6730,  16.7418,  -1.0880,
            4.8576,   9.8855,   0.6730,  -4.3427],
         [ -4.9437,  -4.0576,  -0.4493,   0.6730,  28.4563, -12.7935,   5.5838,
            5.2033, -13.6023,  28.4563,  -3.1565],
         [  1.7081,   1.0195,   5.0289,  16.7418, -12.7935,  52.6238,  -6.9039,
           -0.5158,   0.9026, -12.7935,  -1.7012],
         [ -9.0385,   0.6002, -12.9330,  -1.0880,   5.5838,  -6.9039,  33.9555,
           -0.0922,  -0.3648,   5.5838,   6.4365],
         [ -8.6069,   3.7368,   5.0130,   4.8576,   5.2033, 

In [72]:
attention_score = th.softmax(attention_weight, dim=-1)
attention_score

tensor([[1.0000e+00, 7.9314e-13, 2.0930e-13, 6.0535e-13, 1.2257e-14, 9.4891e-12,
         2.0421e-16, 3.1442e-16, 1.3606e-11, 1.2257e-14, 5.6981e-12],
        [4.7097e-11, 1.0000e+00, 6.5909e-11, 5.8138e-08, 1.7655e-12, 2.8302e-10,
         1.8610e-10, 4.2848e-09, 4.9546e-07, 1.7655e-12, 1.6634e-13],
        [1.7537e-14, 9.3000e-14, 1.0000e+00, 1.3361e-11, 9.1936e-14, 2.2010e-11,
         3.4824e-19, 2.1663e-11, 1.1140e-12, 9.1936e-14, 1.5214e-13],
        [1.4189e-16, 2.2949e-13, 3.7379e-14, 1.0000e+00, 7.9008e-16, 7.5202e-09,
         1.3579e-16, 5.1882e-14, 7.9177e-12, 7.9008e-16, 5.2402e-18],
        [1.5614e-15, 3.7874e-15, 1.3977e-13, 4.2938e-13, 5.0000e-01, 6.0872e-19,
         5.8283e-11, 3.9838e-11, 2.7111e-19, 5.0000e-01, 9.3259e-15],
        [7.7192e-23, 3.8772e-23, 2.1369e-21, 2.6099e-16, 3.8872e-29, 1.0000e+00,
         1.4043e-26, 8.3515e-24, 3.4495e-23, 3.8872e-29, 2.5524e-24],
        [2.1280e-19, 3.2658e-15, 4.3310e-21, 6.0369e-16, 4.7678e-13, 1.7989e-18,
         1.00

In [74]:
all_context_vector = attention_score @ input_embedding
all_context_vector.shape

torch.Size([11, 30])